import os
from logging.handlers import RotatingFileHandler
import logging

# config.py
API_ID = 21851558
API_HASH = "045a99f29cbc003618d9786d0b4683d0"
SESSION_STRING = "AQFNbaYADerHlJEzoFs2v7I5pXNFWD8Alm2_gXdJPCPA-L_k8i1b4Yby4qRP0U74UFLlxeRPZDzLOfV1hD5Cv9BbbKJPCqAlrEWtqVqWH1AdQ6VezrBGdgdmh5SrjG49W5yd5S5XKHTtABmYWS-VpW-fNX8jkpADufZA9iefTuq7nQVY-m5C9tt3om0nDimIdeNCWnHzxTtPbGpaDwM-LXBThWZxKEweecDkqqPJgEyzmaqjlVmqqMfNEAf7Mc-bUbQzTjAz3MdN6YTKgrA1NhkYudlbbc1wavPQ44xQwyrsXncfarIiYyhHCS0YzWhNEw22MOAkx7FO-0ig7EtgZHQQ5lte2gAAAAAkChxkAA"
BOT_TOKEN = "7647640739:AAGk1I_QdLdj9ym8g8Qz3Bk0BK5id5fKYsc"
COOKIES_GIST_URL = "https://gist.githubusercontent.com/dvrajput/8d76c1c85e9f9bf6035ee4a14884121a/raw/a186db5de73d8be8800cfba2fb51d9506a239ef1/ytcookies.txt"
YOUTUBE_COOKIES = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750579350	__Secure-3PSID	g.a000rghxeHySFNem7hvsVAolmFCTlZvUaofCo_NfQGWqKhgS_Rdzpy-78Zl3XE5OcnuFBK4z6AACgYKAaUSARMSFQHGX2MimV5SMvwiEvmjL8UCIulhVBoVAUF8yKrRTgJSUqiC209G9ltsZ_7f0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750832078	__Secure-1PSIDTS	sidts-CjEB7wV3sYqQ68D2RRSzR_emMZhIl4hop63TWclWJq5m-cqvd2eOpXCAAVUf9C8EhqkpEAA
.youtube.com	TRUE	/	TRUE	1750579350	SAPISID	LEde19zuv3DoxJct/A519oa7YVIBRqzPRZ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750832489	__Secure-1PSIDCC	AKEyXzUzDXnL5RrAufWYNg2vkRfMIPHAETGJqklRyKSXbiM8NFb6K60GlN1eOs02qqsaRp6p1w
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750579350	SSID	A9_VJuaoOiRP55Zwc
.youtube.com	TRUE	/	TRUE	1750579350	__Secure-1PAPISID	LEde19zuv3DoxJct/A519oa7YVIBRqzPRZ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750579350	__Secure-1PSID	g.a000rghxeHySFNem7hvsVAolmFCTlZvUaofCo_NfQGWqKhgS_RdzomRZipEW6OggN20MPA4ZQAACgYKAXESARMSFQHGX2Mi5wGVHlnwcL4jT63VuR9_choVAUF8yKrnEl4sr_qXyyN_qn00hEmT0076
.youtube.com	TRUE	/	TRUE	1750579350	__Secure-3PAPISID	LEde19zuv3DoxJct/A519oa7YVIBRqzPRZ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750832489	__Secure-3PSIDCC	AKEyXzWd-kpmR8h7MEASWaawBB0B-OdiZQRL6WH-JSnjdAHPPDOhKLpi2CtUQO_izAETGFw4dw
#HttpOnly_.youtube.com	TRUE	/	TRUE	1750832078	__Secure-3PSIDTS	sidts-CjEB7wV3sYqQ68D2RRSzR_emMZhIl4hop63TWclWJq5m-cqvd2eOpXCAAVUf9C8EhqkpEAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1748665608	LOGIN_INFO	AFmmF2swRgIhAK2Qn8aNAGHfubWXjegCqMeVay7ZEgCRDEjYMqpBnZeGAiEA-H9NZjrtU9iPyfT96iL5WOkVfVs_e2SV7Lwi1Tb0tYo:QUQ3MjNmemFJRlJxUkxTSGFmWkpLeVhHRkRGME9pYXBHaUI4TlJUZVZPajRfWU5QTEM4Uk56WHFFNE1Nc0RrWURWclB0c1huQjlsX0xQTXVmbFlqd3FfcEkwUDRuRTA2UWR6cEJpWUlRX1ptRk9fRmpzWmd2VTFhbmwyT05MMEtPbFF6LWR3OWF2eTlGbzFyNUdTVnJZWS1ISWdwZTl4eE5R
.youtube.com	TRUE	/	TRUE	1735885286	PREF	f6=40000000&tz=Asia.Calcutta&f7=100&f5=30000"""  # Replace with your gist raw URL
LOG_CHANNEL = -1002237500924
DOWNLOAD_DIR = "downloads/"
if not os.path.exists(DOWNLOAD_DIR):
    os.makedirs(DOWNLOAD_DIR)
